package com.codex.neonsprint

import android.graphics.Color

data class CarSpec(
    val id: String,
    val name: String,
    val accent: Int,
    val accentDark: Int,
    val topSpeed: Float,
    val acceleration: Float,
    val braking: Float,
    val grip: Float,
    val handling: Float,
    val drift: Float,
    val mass: Float,
)

val neonGarage = listOf(
    CarSpec(
        id = "falcon_gt",
        name = "Falcon GT",
        accent = Color.rgb(86, 214, 255),
        accentDark = Color.rgb(13, 95, 190),
        topSpeed = 92f,
        acceleration = 26f,
        braking = 32f,
        grip = 1.05f,
        handling = 0.95f,
        drift = 0.22f,
        mass = 1.0f,
    ),
    CarSpec(
        id = "lynx_drift",
        name = "Lynx Drift",
        accent = Color.rgb(255, 111, 178),
        accentDark = Color.rgb(158, 33, 106),
        topSpeed = 88f,
        acceleration = 24f,
        braking = 28f,
        grip = 0.82f,
        handling = 1.18f,
        drift = 0.72f,
        mass = 0.92f,
    ),
    CarSpec(
        id = "vortex_r",
        name = "Vortex R",
        accent = Color.rgb(255, 180, 92),
        accentDark = Color.rgb(170, 78, 12),
        topSpeed = 101f,
        acceleration = 30f,
        braking = 30f,
        grip = 0.94f,
        handling = 1.02f,
        drift = 0.34f,
        mass = 0.98f,
    ),
    CarSpec(
        id = "titan_x",
        name = "Titan X",
        accent = Color.rgb(151, 255, 126),
        accentDark = Color.rgb(43, 132, 63),
        topSpeed = 84f,
        acceleration = 20f,
        braking = 35f,
        grip = 1.18f,
        handling = 0.82f,
        drift = 0.16f,
        mass = 1.22f,
    ),
    CarSpec(
        id = "aether_proto",
        name = "Aether Proto",
        accent = Color.rgb(180, 138, 255),
        accentDark = Color.rgb(83, 58, 177),
        topSpeed = 108f,
        acceleration = 34f,
        braking = 29f,
        grip = 0.9f,
        handling = 1.06f,
        drift = 0.28f,
        mass = 0.9f,
    ),
    CarSpec(
        id = "comet_sr",
        name = "Comet SR",
        accent = Color.rgb(255, 104, 104),
        accentDark = Color.rgb(174, 31, 50),
        topSpeed = 95f,
        acceleration = 27f,
        braking = 33f,
        grip = 1.08f,
        handling = 0.9f,
        drift = 0.18f,
        mass = 1.08f,
    ),
)
